
pull_request_rules:
  - name: Automatic merge on approval + Automatic merge trusted PRs
    conditions: []
    actions:
      queue:
queue_rules:
  - name: duplicated default from Automatic merge on approval
    queue_conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=do-not-merge
      - check-success="success"
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - check-success="Successful build"
    merge_method: merge
  - name: duplicated default from Automatic merge trusted PRs
    queue_conditions:
      - and:
          - or:
              - author=JohnStrunk
              - author=renovate-bot
      - "#changes-requested-reviews-by=0"
      - label!=do-not-merge
      - check-success="Successful build"
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - check-success="Successful build"
    merge_method: merge
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success="Successful build"
