---
name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f  # v3.4.0

      - name: Install deps
        run: npm install

      - name: Install angular-cli
        run: npm install -g @angular/cli

      - name: Build
        run: ng build
