---
name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b  # v3.2.0

      - name: Install deps
        run: npm install

      - name: Install angular-cli
        run: npm install -g @angular/cli

      - name: Build
        run: ng build
