---
name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b  # v3.2.0

    - name: Build and deploy
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@0e4f1a953d00116ca38fbf1bcdb37f91923015ef  # v1.3.2
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        build_configuration: production
        base_href: /DigitFidget/
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/digit-fidget
