---
# https://vite.dev/guide/static-deploy.html#github-pages
name: Build & Deploy
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  workflow_dispatch:


concurrency:
  group: "pages"
  cancel-in-progress: true


jobs:
  build:
    name: "Build & deploy"
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # https://github.com/actions/setup-node
      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          cache: yarn

      - name: Install packages
        run: yarn install --immutable

      - name: Build
        run: yarn run build

      # https://github.com/actions/configure-pages
      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      # https://github.com/actions/upload-pages-artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          # Upload dist folder
          path: './dist'

      # https://github.com/actions/deploy-pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
