---
name: Build & Test
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:

jobs:
  pre-commit:
    name: "Pre-commit checks"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        # https://github.com/actions/setup-python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        id: python

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Enable cache for pre-commit hooks
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ steps.python.outputs.python-version }}|${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit|${{ steps.python.outputs.python-version }}|
            pre-commit|

      - name: Run pre-commit checks
        run: pre-commit run -a

      - name: Run pre-commit gc
        run: pre-commit gc

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/actions/setup-node
      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          cache: yarn

      - name: Install packages
        run: yarn install --immutable

      - name: Run tests
        run: yarn run test

      - name: Build
        run: yarn run build

  success:
    name: "Successful build"
    runs-on: ubuntu-latest
    needs: [build, pre-commit]
    steps:
      - name: Success
        run: echo "Checks succeeded!"
