---
# https://www.viget.com/articles/host-build-and-deploy-next-js-projects-on-github-pages/
name: Build & Test
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:

jobs:
  pre-commit:
    name: "Pre-commit checks"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        # https://github.com/actions/setup-python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Enable cache for pre-commit hooks
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit|${{ env.pythonLocation }}
            pre-commit|

      - name: Run pre-commit checks
        run: pre-commit run -a

      - name: Run pre-commit gc
        run: pre-commit gc

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/actions/setup-node
      - name: Set up Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 22
          cache: npm

      - name: Install packages
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

  success:
    name: "Successful build"
    runs-on: ubuntu-latest
    needs: [build, pre-commit]
    steps:
      - name: Success
        run: echo "Checks succeeded!"
