---
name: Build & Test
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:

jobs:
  pre-commit:
    name: "Pre-commit checks"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Python
        # https://github.com/actions/setup-python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        id: python

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Enable cache for pre-commit hooks
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ steps.python.outputs.python-version }}|${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit|${{ steps.python.outputs.python-version }}|
            pre-commit|

      - name: Run pre-commit checks
        run: pre-commit run -a

      - name: Run pre-commit gc
        run: pre-commit gc

  # build:
  #   name: "Build"
  #   runs-on: ubuntu-latest
  #   steps:
  #     # https://github.com/actions/checkout
  #     - name: Checkout repository
  #       uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

  #     - name: Set up Node
  #       # https://github.com/actions/setup-node
  #       uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
  #       with:
  #         node-version: lts/*
  #         # Disable automatic caching due to incompatibility w/ corepack
  #         # https://github.com/actions/setup-node/issues/531
  #         package-manager-cache: false

  #     - name: Enable corepack
  #       run: corepack enable

  #     # https://github.com/actions/cache/blob/main/examples.md#node---yarn-2
  #     - name: Get yarn cache directory path
  #       id: yarn-cache-dir-path
  #       run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

  #     - name: Enable yarn cache
  #       # https://github.com/actions/cache
  #       uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
  #       id: yarn-cache
  #       with:
  #         path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
  #         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-yarn-

  #     - name: Install packages
  #       run: yarn install --immutable

  #     - name: Run tests
  #       run: yarn run test

  #     - name: Build
  #       run: yarn run build

  success:
    name: "Successful build"
    runs-on: ubuntu-latest
    # needs: [build, pre-commit]
    needs: [pre-commit]
    steps:
      - name: Success
        run: echo "Checks succeeded!"
