---
name: Build & Test
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:

jobs:
  pre-commit:
    name: "Pre-commit checks"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        # https://github.com/actions/setup-python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        id: python

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Enable cache for pre-commit hooks
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ steps.python.outputs.python-version }}|${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit|${{ steps.python.outputs.python-version }}|
            pre-commit|

      - name: Run pre-commit checks
        run: pre-commit run -a

      - name: Run pre-commit gc
        run: pre-commit gc

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/actions/setup-node
      - name: Set up Node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 22
          cache: npm

      - name: Install packages
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

  success:
    name: "Successful build"
    runs-on: ubuntu-latest
    needs: [build, pre-commit]
    steps:
      - name: Success
        run: echo "Checks succeeded!"
